// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/10/2025, 12:45:42
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/davidrodriguezpozo/workspaces/invoice_generator/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/plugins/**/*.{js,ts,mjs}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/composables/**/*.{js,ts,mjs}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/utils/**/*.{js,ts,mjs}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/davidrodriguezpozo/workspaces/invoice_generator/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;